# Reference documentation: https://help.metrics.ca/support/solutions/articles/154000141157-dsim-cloud-configuration
toolchain:
  environment-variables: # Define environment variables
    # HELLO: world
  packages: # Include packages
    - name: ieee
      version: "93"
    # - name: quartus
    #   version: "22.2"
    # - name: vivado
    #   version: "2022.1"
    # - name: uvm
    #   version: "1.2"
  dsim:
    # version: "20220822.x.x" # Optional. Defaults to the latest version available. Uncomment to set a specific version.
